---
title: "Data manipulation with “dplyr”"
author: "zz3039"
date: "2022-09-22"
output: html_document
---

```{r chunk_start with}
library(tidyverse)
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)
view(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
view(pups_data)
```

```{r chunk_function_select, eval=FALSE}
# select(tibble, variable1, variable2, ...)
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
select(litters_data, group:gd_of_birth)
select(litters_data, -pups_survive)
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
select(litters_data, starts_with("gd"))
select(litters_data, litter_number, pups_survive, everything())
relocate(litters_data, litter_number, pups_survive)

# Learning Assessment: In the pups data, select the columns containing litter number, sex, and PD ears.
select(pups_data, litter_number, sex, pd_ears)
```

```{r chunk_function_filter, eval=FALSE}
filter(litters_data, gd_of_birth == 20)
filter(litters_data, pups_born_alive >= 2)
filter(litters_data, pups_survive != 4)
filter(litters_data, !(pups_survive == 4))
filter(litters_data, group %in% c("Con7", "Con8"))
filter(litters_data, group == "Con7" & gd_of_birth == 20)
filter(litters_data, drop_na(litters_data))
filter(litters_data, drop_na(litters_data, wt_increase) )

# Learning Assessment: In the pups data:
# Filter to include only pups with sex 1
# Filter to include only pups with PD walk less than 11 and sex 2
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```

```{r chunk_function_mutate, eval=FALSE}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)

# Learning Assessment: In the pups data:
# Create a variable that subtracts 7 from PD pivot
# Create a variable that is the sum of all the PD variables
mutate(pups_data, 
       pd_ears = pd_ears - 7,
       pd_eyes = pd_eyes - 7,
       pd_pivot = pd_pivot - 7,
       pd_walk = pd_walk - 7,
       pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
# sum changed
```

```{r chunk_function_arrage, eval=FALSE}
head(arrange(litters_data, group, pups_born_alive), 10)

```

```{r chunk_pipe, eval=FALSE}
# %>% "and then"
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
```

```{r chunk_dplyr, eval=FALSE}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(data = ., wt_gain)
# the dataset argument is called dat in janitor::clean_names, .data in the dplyr functions, and data in drop_na

# Learning Assessment: Write a chain of commands that:
# loads the pups data
# cleans the variable names
# filters the data to include only pups with sex 1
# removes the PD ears variable
# creates a variable that indicates whether PD pivot is 7 or more days
```




