---
title: "Data Wrangling 1"
output: github_document
---

This is the repo associated with code for lectures in data wrangling 1 in p8105.

## Data Import: CSVs

Let's import data using the 'readr' package.

```{r chunk_import data, echo=FALSE}
library(tidyverse)

litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
litters_data = janitor::clean_names(litters_data)
litters_data
# use function"clean-names" in janitor without downloading the whole package.
```


```{r chunk_functions}
litters_data

tail(litters_data, 5)

skimr::skim(litters_data)

# view(litters_data) useful, but may go wrong in git

```
'read_csv' options ..

```{r chunk_missing data or mess}
read_csv(file = "./data/FAS_litters.csv",
         na = c("", "NA", 000, 999), 
         skip = 2, 
         col_names = FALSE)
```








